# Generated by Django 5.2.4 on 2025-08-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='is_active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
