services:
  mysql:
    image: mysql:8
    container_name: jump_to_django-mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
      - ./.docker/mysql/my.cnf:/etc/mysql/mysql.conf.d/custom.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: django
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    networks:
      - local_network

  mongo:
    image: mongo:latest
    container_name: jump_to_django-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./.docker/mongo/data:/data/db
    ports:
      - "27017:27017"
    networks:
      - local_network

  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: jump_to_django
    volumes:
      - ./:/app
    ports:
      - "9096:8000"
    networks:
      - local_network
    environment:
      DB_HOST: jump_to_django-mysql
      MONGO_DB_HOST: jump_to_django-mongodb      

networks:
  local_network:
    driver: bridge
